data_root: dataset
img_size: 512
train:
  batch_size: 4
  epochs: 40
  lr: 0.0001  # Reduced LR to prevent gradient explosion
  weight_decay: 0.0001
  amp: true
  num_workers: 4
  seed: 42
scheduler:
  type: "cosine_annealing"  # Options: cosine_annealing, step, exponential, reduce_on_plateau
  # For cosine_annealing
  T_max: 100  # Total epochs
  eta_min: 0.00001  # Minimum LR
  # For step scheduler
  step_size: 20
  gamma: 0.5
  # For exponential
  gamma_exp: 0.95
  # For reduce_on_plateau
  patience: 5
  factor: 0.5
  min_lr: 0.00001
model:
  base_channels: 96
  num_attn_blocks: 3
  num_heads: 8
  use_gan: false  # Disabled temporarily to prevent instability
loss_weights:
  w_l1: 1.0
  w_de: 0.5
  w_perc: 0.01  # Drastically reduced perceptual loss weight
  w_gan: 0.0  # Disabled with use_gan: false
  w_color: 0.3  # Color alignment loss (explicit color matching)
degrade:
  enable: true
  mode: mixed
  magnitude: 0.15  # Increased from 0.06 to 0.15 for visible degradation
val:
  every_n_epochs: 2
early_stopping:
  enabled: true
  patience: 15  # Stop after 15 epochs without improvement
  min_delta: 0.001  # Minimum improvement threshold
  mode: "min"  # Monitor metric should decrease (Delta E)
  restore_best_weights: true
save_dir: runs/model1_recolor
