data_root: dataset
img_size: 512
train:
  batch_size: 8
  epochs: 20 #60
  lr: 1.0e-4
  weight_decay: 0.0
  amp: true
  num_workers: 2
  seed: 42
model:
  base_channels: 64
  num_attn_blocks: 2
  num_heads: 4
  use_gan: false
loss_weights:
  w_l1: 1.0
  w_de: 1.0
  w_perc: 0.1
  w_gan: 0.0
degrade:
  enable: true
  mode: lab
  magnitude: 0.04
val:
  every_n_epochs: 1
save_dir: runs/model1_recolor
