data_root: dataset
img_size: 512
train:
  batch_size: 4
  epochs: 100
  lr: 0.0002  # Higher initial LR for scheduler
  weight_decay: 0.0001
  amp: true
  num_workers: 4
  seed: 42
scheduler:
  type: "cosine_annealing"  # Options: cosine_annealing, step, exponential, reduce_on_plateau
  # For cosine_annealing
  T_max: 100  # Total epochs
  eta_min: 0.00001  # Minimum LR
  # For step scheduler
  step_size: 20
  gamma: 0.5
  # For exponential
  gamma_exp: 0.95
  # For reduce_on_plateau
  patience: 5
  factor: 0.5
  min_lr: 0.00001
model:
  base_channels: 96
  num_attn_blocks: 3
  num_heads: 8
  use_gan: true
loss_weights:
  w_l1: 0.5
  w_de: 2.0
  w_perc: 0.3
  w_gan: 0.1
degrade:
  enable: true
  mode: mixed
  magnitude: 0.06
val:
  every_n_epochs: 1
save_dir: runs/model1_recolor
