data_root: dataset
img_size: 512
train:
  batch_size: 16
  epochs: 25 #50
  lr: 5.0e-5
  weight_decay: 1e-4
  amp: true
  num_workers: 4
  seed: 42
seg:
  threshold: 0.4
augment:
  hflip: true
  rotate_deg: 15
  scale: [0.8, 1.2]
  brightness: [0.8, 1.2]
  contrast: [0.8, 1.2]
val:
  every_n_epochs: 1
save_dir: runs/model3_seg_onmodel
