data_root: dataset
img_size: 512
train:
  batch_size: 8
  epochs: 5 #50
  lr: 1.0e-4
  weight_decay: 0.0
  amp: true
  num_workers: 2
  seed: 42
seg:
  threshold: 0.5
augment:
  hflip: true
  rotate_deg: 5
  scale: [0.95, 1.05]
val:
  every_n_epochs: 1
save_dir: runs/model2_seg_still
