data_root: dataset
img_size: 512
train:
  batch_size: 4
  epochs: 80
  lr: 5.0e-5
  weight_decay: 1e-4
  amp: true
  num_workers: 4
  seed: 42
model:
  base_channels: 96
  num_attn_blocks: 3
  num_heads: 8
  use_gan: true
loss_weights:
  w_l1: 0.5
  w_de: 2.0
  w_perc: 0.3
  w_gan: 0.1
degrade:
  enable: true
  mode: lab
  magnitude: 0.06
val:
  every_n_epochs: 1
save_dir: runs/model1_recolor
