data_root: dataset
img_size: 512
train:
  batch_size: 16
  epochs: 40 #50
  lr: 0.0001  # Higher initial LR for scheduler
  weight_decay: 0.0001
  amp: true
  num_workers: 4
  seed: 42
scheduler:
  type: "cosine_annealing"  # Options: cosine_annealing, step, exponential, reduce_on_plateau
  # For cosine_annealing
  T_max: 40  # Total epochs
  eta_min: 0.00001  # Minimum LR
  # For step scheduler
  step_size: 10
  gamma: 0.5
  # For exponential
  gamma_exp: 0.96
  # For reduce_on_plateau
  patience: 4
  factor: 0.5
  min_lr: 0.00001
seg:
  threshold: 0.4
augment:
  hflip: true
  rotate_deg: 15
  scale: [0.8, 1.2]
  brightness: [0.8, 1.2]
  contrast: [0.8, 1.2]
val:
  every_n_epochs: 2
early_stopping:
  enabled: true
  patience: 10  # Stop after 10 epochs without improvement
  min_delta: 0.001  # Minimum improvement threshold
  mode: "max"  # Monitor metric should increase (IoU)
  restore_best_weights: true
save_dir: runs/model3_seg_onmodel
